### ISSUE TITLE
Reliance on torrentmanager attribute

### ISSUE THREAD

**Issue by cas--** [ratanakvlun/deluge-movetools#1]
Although it's redundant tool now as move progress is shown. Just a heads-up that a user was testing this plugin on Deluge 2.0b1 and encountered the following error:

```
09:29:37.129 [ERROR   ][deluge.pluginmanagerbase                           :183 ] Failed to start plugin: MoveTools
Traceback: <type 'exceptions.AttributeError'>: 'TorrentManager' object has no attribute 'session_started'
/usr/lib/python2.7/site-packages/twisted/internet/defer.py:150:maybeDeferred
/usr/lib/python2.7/site-packages/deluge/plugins/init.py:27:enable
/home/............/.config/deluge/plugins/MoveTools-0.2.0.2-py2.7.egg/movetools/core.py:179:enable
```

The attribute `torrentmanager.session_started` was a workaround and shouldn't really be accessed publicly and it is not available in 2.0. 

If you have an requests for changes to the deluge api let me know, ideally before I release 2.0 ;)

**Comment by ratanakvlun** [comment]
Thanks. I'll keep that in mind when porting my plugins to 2.0.
